<?xml version="1.0" ?>
<robot name="$(arg robotName)" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find car_description)/src/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find car_description)/src/urdf/car_gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

    <!-- #### constants #### -->
    <xacro:property name="deg_to_rad" value="0.017453"/>
    <xacro:property name="PI" value="3.14"/>

    <xacro:macro name="cylinder_inertia" params ="m r h"> 
        <inertial> 
            <mass value="${m}"/> 
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                     iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                     izz="${m*r*r/2}"/> 
         </inertial> 
     </xacro:macro>

    <!-- #### chassis property #### -->
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.05"/>

    <!-- ####  caster property #### -->
    <xacro:property name="caster_radius" value="0.025"/>
    <xacro:property name="caster_length" value="0.015"/>
    <xacro:property name="caster_mass" value="0.2"/>


    <!-- #####  caster macro   ##### -->

    <xacro:macro name="caster" params= "prefix suffix X1 X2 Y1 Y2">
                     
      <joint name="${prefix}_${suffix}_caster_joint" type="fixed">
        <parent link= "chassis"/>
        <child link= "${prefix}_${suffix}_caster"/>
        <origin xyz= "${(chassis_length/2)*X1 + (chassis_length/2-.05)*X2} ${(chassis_width/2-0.02)*Y1 + (chassis_width/2)*Y2}  0.026" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>
               
      <link name= "${prefix}_${suffix}_caster">
        <visual>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 -0.025"/>
          <geometry>
              <mesh filename="package://car_description/src/meshes/caster.stl" scale="0.0002 0.0002 0.0002"/>
          </geometry>
          <material name= "grey"/>
        </visual>
        <collision>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
          <geometry>
            <cylinder length="${caster_length}" radius= "${caster_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${caster_mass}" r="${caster_radius}" h="${caster_length}"/>
      </link>
             
         
      <gazebo reference ="${prefix}_${suffix}_caster">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
        <kp value="10000000.0"/>
        <kd value= "1.0"/>
        <material>Gazebo/WhiteGlow</material>
      </gazebo>
    </xacro:macro>

  <link name="base_footprint"/>

<!-- #####   BEGIN  ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="chassis" />
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="15"/>
      <inertia ixx="1.15625e-01" ixy="0" ixz="0"
               iyy="1.15625e-01" iyz="0"
               izz="2.25e-01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 ${chassis_width/2-0.05} 0.033" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://car_description/src/meshes/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -${chassis_width/2-0.05} 0.033" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://car_description/src/meshes/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!-- #### 4 casters  #### -->
  <xacro:caster prefix="right" suffix="front" X1="0" X2="1" Y1="-1" Y2="0" />
  <xacro:caster prefix="right" suffix="back" X1="-1" X2="0" Y1="-1" Y2="0"/>
  <xacro:caster prefix="left" suffix="front" X1="0" X2="1" Y1="0" Y2="1"/>
  <xacro:caster prefix="left" suffix="back" X1="-1" X2="0" Y1="0" Y2="1"/>

<!-- #### Sensors : Lidar #### -->
  
  <joint name="scan_joint1" type="fixed">
    <parent link="chassis"/>
    <child link="scan_lidar"/>
    <!-- <origin xyz="${chassis_length/2-0.03} ${chassis_width/2-0.03} 0.16" rpy="0 0 -${PI/2}"/> -->
    <origin xyz="0 0 0.16" rpy="0 0 0"/>
    
  </joint>

  <link name="scan_lidar">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://car_description/src/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="black"/>
    </visual>

    <!-- <collision>
      <origin xyz="0 0 -.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision> -->

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

<!-- Sensors : IMU -->
  <joint name="imu_joint" type="fixed">
      <parent link="chassis"/>
      <child link="imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  <link name="imu_link">
    <!-- <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://car_description/src/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="black"/>
    </visual> -->

    <!-- <collision>
      <origin xyz="0 0 -.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial> -->
  </link>


<!-- Begin of camera -->


</robot>